name = "Iuppiter-2"
author = "Losenone, Filostorm"
version = "0.9.3-r3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e2a791bc87b998e0db059bdf1f80186dff0f632c4bde7052552f28320e65995"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
