name = "Iuppiter-2"
author = "Losenone, Filostorm"
version = "0.9.3-r2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc55a696ff080c85200fe8800760fd5219a4aa5a51c8cc8d7e53482f0234ebf6"

[versions]
forge = "40.2.17"
minecraft = "1.18.2"
